annotation.processing.enabled=true
annotation.processing.enabled.in.editor=false
annotation.processing.processor.options=
annotation.processing.processors.list=
annotation.processing.run.all.processors=true
annotation.processing.source.output=${r"${build.generated.sources.dir}"}/ap-source-output
build.classes.dir=${r"${build.dir}"}/classes
build.classes.excludes=**/*.java,**/*.form
# This directory is removed when the project is cleaned:
build.dir=build
build.generated.dir=${r"${build.dir}"}/generated
build.generated.sources.dir=${r"${build.dir}"}/generated-sources
# Only compile against the classpath explicitly listed here:
build.sysclasspath=ignore
build.test.classes.dir=${r"${build.dir}"}/test/classes
build.test.results.dir=${r"${build.dir}"}/test/results
# Uncomment to specify the preferred debugger connection transport:
#debug.transport=dt_socket
debug.classpath=\
    ${r"${run.classpath}"}
debug.test.classpath=\
    ${r"${run.test.classpath}"}
# This directory is removed when the project is cleaned:
dist.dir=dist
dist.jar=${r"${dist.dir}"}/dynamicreports-examples.jar
dist.javadoc.dir=${r"${dist.dir}"}/javadoc
excludes=
file.reference.activation-${project.activationVersion}.jar=lib\\activation-${project.activationVersion}.jar
file.reference.avalon-framework-impl-${project.avalonframeworkimplVersion}.jar=lib\\avalon-framework-impl-${project.avalonframeworkimplVersion}.jar
file.reference.barcode4j-${project.barcode4jVersion}.jar=lib\\barcode4j-${project.barcode4jVersion}.jar
file.reference.barbecue-${project.barbecueVersion}.jar=lib\\barbecue-${project.barbecueVersion}.jar
file.reference.batik-anim-${project.batikbridgeVersion}.jar=lib\\batik-anim-${project.batikbridgeVersion}.jar
file.reference.batik-awt-util-${project.batikbridgeVersion}.jar=lib\\batik-awt-util-${project.batikbridgeVersion}.jar
file.reference.batik-bridge-${project.batikbridgeVersion}.jar=lib\\batik-bridge-${project.batikbridgeVersion}.jar
file.reference.batik-css-${project.batikbridgeVersion}.jar=lib\\batik-css-${project.batikbridgeVersion}.jar
file.reference.batik-dom-${project.batikbridgeVersion}.jar=lib\\batik-dom-${project.batikbridgeVersion}.jar
file.reference.batik-ext-${project.batikbridgeVersion}.jar=lib\\batik-ext-${project.batikbridgeVersion}.jar
file.reference.batik-gvt-${project.batikbridgeVersion}.jar=lib\\batik-gvt-${project.batikbridgeVersion}.jar
file.reference.batik-parser-${project.batikbridgeVersion}.jar=lib\\batik-parser-${project.batikbridgeVersion}.jar
file.reference.batik-script-${project.batikbridgeVersion}.jar=lib\\batik-script-${project.batikbridgeVersion}.jar
file.reference.batik-svg-dom-${project.batikbridgeVersion}.jar=lib\\batik-svg-dom-${project.batikbridgeVersion}.jar
file.reference.batik-util-${project.batikbridgeVersion}.jar=lib\\batik-util-${project.batikbridgeVersion}.jar
file.reference.batik-xml-${project.batikbridgeVersion}.jar=lib\\batik-xml-${project.batikbridgeVersion}.jar
file.reference.bcprov-jdk14-${project.bcprovjdk14Version}.jar=lib\\bcprov-jdk14-${project.bcprovjdk14Version}.jar
file.reference.commons-beanutils-${project.commonsbeanutilsVersion}.jar=lib\\commons-beanutils-${project.commonsbeanutilsVersion}.jar
file.reference.commons-collections-${project.commonscollectionsVersion}.jar=lib\\commons-collections-${project.commonscollectionsVersion}.jar
file.reference.commons-digester-${project.commonsdigesterVersion}.jar=lib\\commons-digester-${project.commonsdigesterVersion}.jar
file.reference.commons-lang-${project.commonslangVersion}.jar=lib\\commons-lang-${project.commonslangVersion}.jar
file.reference.commons-lang3-${project.commonslang3Version}.jar=lib\\commons-lang3-${project.commonslang3Version}.jar
file.reference.commons-logging-${project.commonsloggingVersion}.jar=lib\\commons-logging-${project.commonsloggingVersion}.jar
file.reference.dynamicreports-core-${project.version}.jar=lib\\dynamicreports-core-${project.version}.jar
file.reference.dynamicreports-adhoc-${project.version}.jar=lib\\dynamicreports-adhoc-${project.version}.jar
file.reference.dynamicreports-googlecharts-${project.version}.jar=lib\\dynamicreports-googlecharts-${project.version}.jar
file.reference.itext-${project.itextVersion}.jar=lib\\itext-${project.itextVersion}.jar
file.reference.jasperreports-${project.jasperreportsVersion}.jar=lib\\jasperreports-${project.jasperreportsVersion}.jar
file.reference.jaxb-api-${project.jaxbimplVersion}.jar=lib\\jaxb-api-${project.jaxbimplVersion}.jar
file.reference.jaxb-impl-${project.jaxbimplVersion}.jar=lib\\jaxb-impl-${project.jaxbimplVersion}.jar
file.reference.jcommon-${project.jcommonVersion}.jar=lib\\jcommon-${project.jcommonVersion}.jar
file.reference.jdtcore-${project.jdtcoreVersion}.jar=lib\\jdtcore-${project.jdtcoreVersion}.jar
file.reference.jfreechart-${project.jfreechartVersion}.jar=lib\\jfreechart-${project.jfreechartVersion}.jar
file.reference.jxl-${project.jxlVersion}.jar=lib\\jxl-${project.jxlVersion}.jar
file.reference.jackson-core-lgpl-${project.jacksonVersion}.jar=lib\\jackson-core-lgpl-${project.jacksonVersion}.jar
file.reference.jackson-mapper-lgpl-${project.jacksonVersion}.jar=lib\\jackson-mapper-lgpl-${project.jacksonVersion}.jar
file.reference.log4j-${project.log4jVersion}.jar=lib\\log4j-${project.log4jVersion}.jar
file.reference.poi-${project.poiVersion}.jar=lib\\poi-${project.poiVersion}.jar
file.reference.stax-api-${project.staxapiVersion}.jar=lib\\stax-api-${project.staxapiVersion}.jar
file.reference.xml-apis-${project.xmlapisVersion}.jar=lib\\xml-apis-${project.xmlapisVersion}.jar
file.reference.xml-apis-ext-${project.xmlapisVersion}.jar=lib\\xml-apis-ext-${project.xmlapisVersion}.jar
file.reference.spring-core-${project.springframeworkVersion}.jar=lib\\spring-core-${project.springframeworkVersion}.jar
file.reference.spring-beans-${project.springframeworkVersion}.jar=lib\\spring-beans-${project.springframeworkVersion}.jar
file.reference.hsqldb-${project.hsqldbVersion}.jar=lib\\hsqldb-${project.hsqldbVersion}.jar
file.reference.xalan-${project.xalanVersion}.jar=lib\\xalan-${project.xalanVersion}.jar
file.reference.serializer-${project.xalanVersion}.jar=lib\\serializer-${project.xalanVersion}.jar
file.reference.velocity-${project.velocityVersion}.jar=lib\\velocity-${project.velocityVersion}.jar
file.reference.json-${project.jsonVersion}.jar=lib\\json-${project.jsonVersion}.jar
includes=**
jar.compress=false
javac.classpath=\
    ${r"${"}file.reference.activation-${project.activationVersion}.jar${r"}"}:\
    ${r"${"}file.reference.avalon-framework-impl-${project.avalonframeworkimplVersion}.jar${r"}"}:\
    ${r"${"}file.reference.barcode4j-${project.barcode4jVersion}.jar${r"}"}:\
    ${r"${"}file.reference.barbecue-${project.barbecueVersion}.jar${r"}"}:\
    ${r"${"}file.reference.batik-anim-${project.batikbridgeVersion}.jar${r"}"}:\
    ${r"${"}file.reference.batik-awt-util-${project.batikbridgeVersion}.jar${r"}"}:\
    ${r"${"}file.reference.batik-bridge-${project.batikbridgeVersion}.jar${r"}"}:\
    ${r"${"}file.reference.batik-css-${project.batikbridgeVersion}.jar${r"}"}:\
    ${r"${"}file.reference.batik-dom-${project.batikbridgeVersion}.jar${r"}"}:\
    ${r"${"}file.reference.batik-ext-${project.batikbridgeVersion}.jar${r"}"}:\
    ${r"${"}file.reference.batik-gvt-${project.batikbridgeVersion}.jar${r"}"}:\
    ${r"${"}file.reference.batik-parser-${project.batikbridgeVersion}.jar${r"}"}:\
    ${r"${"}file.reference.batik-script-${project.batikbridgeVersion}.jar${r"}"}:\
    ${r"${"}file.reference.batik-svg-dom-${project.batikbridgeVersion}.jar${r"}"}:\
    ${r"${"}file.reference.batik-util-${project.batikbridgeVersion}.jar${r"}"}:\
    ${r"${"}file.reference.batik-xml-${project.batikbridgeVersion}.jar${r"}"}:\
    ${r"${"}file.reference.bcprov-jdk14-${project.bcprovjdk14Version}.jar${r"}"}:\
    ${r"${"}file.reference.commons-beanutils-${project.commonsbeanutilsVersion}.jar${r"}"}:\
    ${r"${"}file.reference.commons-collections-${project.commonscollectionsVersion}.jar${r"}"}:\
    ${r"${"}file.reference.commons-digester-${project.commonsdigesterVersion}.jar${r"}"}:\
    ${r"${"}file.reference.commons-lang-${project.commonslangVersion}.jar${r"}"}:\
    ${r"${"}file.reference.commons-lang3-${project.commonslang3Version}.jar${r"}"}:\
    ${r"${"}file.reference.commons-logging-${project.commonsloggingVersion}.jar${r"}"}:\
    ${r"${"}file.reference.dynamicreports-core-${project.version}.jar${r"}"}:\
    ${r"${"}file.reference.dynamicreports-adhoc-${project.version}.jar${r"}"}:\
    ${r"${"}file.reference.dynamicreports-googlecharts-${project.version}.jar${r"}"}:\
    ${r"${"}file.reference.itext-${project.itextVersion}.jar${r"}"}:\
    ${r"${"}file.reference.jasperreports-${project.jasperreportsVersion}.jar${r"}"}:\
    ${r"${"}file.reference.jaxb-api-${project.jaxbimplVersion}.jar${r"}"}:\
    ${r"${"}file.reference.jaxb-impl-${project.jaxbimplVersion}.jar${r"}"}:\
    ${r"${"}file.reference.jcommon-${project.jcommonVersion}.jar${r"}"}:\
    ${r"${"}file.reference.jdtcore-${project.jdtcoreVersion}.jar${r"}"}:\
    ${r"${"}file.reference.jfreechart-${project.jfreechartVersion}.jar${r"}"}:\
    ${r"${"}file.reference.jxl-${project.jxlVersion}.jar${r"}"}:\
    ${r"${"}file.reference.jackson-core-lgpl-${project.jacksonVersion}.jar${r"}"}:\
    ${r"${"}file.reference.jackson-mapper-lgpl-${project.jacksonVersion}.jar${r"}"}:\
    ${r"${"}file.reference.log4j-${project.log4jVersion}.jar${r"}"}:\
    ${r"${"}file.reference.poi-${project.poiVersion}.jar${r"}"}:\
    ${r"${"}file.reference.stax-api-${project.staxapiVersion}.jar${r"}"}:\
    ${r"${"}file.reference.xml-apis-${project.xmlapisVersion}.jar${r"}"}:\
    ${r"${"}file.reference.xml-apis-ext-${project.xmlapisVersion}.jar${r"}"}:\
    ${r"${"}file.reference.spring-core-${project.springframeworkVersion}.jar${r"}"}:\
    ${r"${"}file.reference.spring-beans-${project.springframeworkVersion}.jar${r"}"}:\
    ${r"${"}file.reference.hsqldb-${project.hsqldbVersion}.jar${r"}"}:\
    ${r"${"}file.reference.xalan-${project.xalanVersion}.jar${r"}"}:\
    ${r"${"}file.reference.serializer-${project.xalanVersion}.jar${r"}"}:\
    ${r"${"}file.reference.velocity-${project.velocityVersion}.jar${r"}"}:\
    ${r"${"}file.reference.json-${project.jsonVersion}.jar${r"}"}
# Space-separated list of extra javac options
javac.compilerargs=
javac.deprecation=false
javac.processorpath=\
    ${r"${javac.classpath}"}
javac.source=1.5
javac.target=1.5
javac.test.classpath=\
    ${r"${javac.classpath}"}:\
    ${r"${build.classes.dir}"}:\
    ${r"${libs.junit.classpath}"}:\
    ${r"${libs.junit_4.classpath}"}
javac.test.processorpath=\
    ${r"${javac.test.classpath}"}
javadoc.additionalparam=
javadoc.author=false
javadoc.encoding=${r"${source.encoding}"}
javadoc.noindex=false
javadoc.nonavbar=false
javadoc.notree=false
javadoc.private=false
javadoc.splitindex=true
javadoc.reference.dynamicreports-core-${project.version}.jar=lib/dynamicreports-core-${project.version}-javadoc.jar
javadoc.use=true
javadoc.version=false
javadoc.windowtitle=
main.class=
manifest.file=manifest.mf
meta.inf.dir=${r"${src.dir}"}/META-INF
platform.active=default_platform
run.classpath=\
    ${r"${javac.classpath}"}:\
    ${r"${build.classes.dir}"}
# Space-separated list of JVM arguments used when running the project
# (you may also define separate properties like run-sys-prop.name=value instead of -Dname=value
# or test-sys-prop.name=value to set system properties for unit tests):
run.jvmargs=
run.test.classpath=\
    ${r"${javac.test.classpath}"}:\
    ${r"${build.test.classes.dir}"}
source.encoding=UTF-8
source.reference.dynamicreports-core-${project.version}.jar=lib/dynamicreports-core-${project.version}-sources.jar
source.reference.dynamicreports-adhoc-${project.version}.jar=lib/dynamicreports-adhoc-${project.version}-sources.jar
source.reference.dynamicreports-googlecharts-${project.version}.jar=lib/dynamicreports-googlecharts-${project.version}-sources.jar
src.dir=src
test.src.dir=test
